# # source database URL
# # database URLs take the format of:
# #   postgres://user:password@host:port/dbname
# #
# # we recommend a command which outputs a database URL
# # so sensitive information is not included in this file
# #
# # we *highly recommend* you use sslmode=verify-full when possible
# # see https://ankane.org/postgres-sslmode-explained for more info
# from: $(some_command)?sslmode=require

# # destination database URL
# to: postgres://localhost:5432/controllerpg_development

# # exclude tables
# exclude:
#   - ar_internal_metadata
#   - schema_migrations

# # define groups
# groups:
#   group1:
#     - dim_customers
#     - fact_quotes
#     - fact_elevator
#     - fact_contact

# # sync specific schemas
# schemas:
#   - schema

# # protect sensitive information
# data_rules:
#   email: unique_email
#   phone: unique_phone
#   last_name: random_letter
#   birthday: random_date
#   encrypted_*: null

  