default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: gabrielrioux
  password: 
  host: localhost
  database: controllerpg_development

controllerpg_development:
  <<: *default
  database: controllerpg_development

controllerpg_test:
  <<: *default
  database: controllerpg_test

controllerpg_production:
  <<: *default
  url: <%= ENV['CONTROLLERPG_DATABASE_URL'] %>